export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Quiz } from "./Quiz";
export { default as Tasks } from "./Tasks";
export { default as Chap } from "./Chap";
export { default as Plus } from "./Plus";
export { default as Subchap } from "./Subchap";
export { default as Logout } from "./Logout";